## Pandas Indexing and Subsetting

This notebooks focuses on understanding indexing and subsetting in Pandas dataframes.

1. How to define a dataframe using a dictionary.
2. How to set index and use access attributes of a dataframe.
3. How to access specific and slices of rows and columns of a dataframe.

In [ ]:
import numpy as np
import pandas as pd
import random
import string

In [ ]:
##create a dictionary that stores 
##students' roll number, math, physics & chem scores.

scores_dict = {
    'id': [''.join(random.choices(
        string.ascii_uppercase + string.digits, k=5)
                 ) for _ in range(30)],
    'roll': np.arange(30) + 1,
    'math_scores': np.random.randint(100, size=(30)),
    'physics_scores': np.random.randint(100, size=(30)),
    'chemistry_scores': np.random.randint(100, size=(30))
}

print(scores_dict)

{'id': ['XFP1Q', 'LXFDN', '1PEXT', 'QAQX0', 'QC0JJ', 'KUJR9', 'IFUWW', 'LRBV9', 'QNKW7', 'YSCXL', 'D0SEA', 'S123C', 'HBLQD', 'GKIW5', 'MJ8N5', 'K8DZ8', '7XQ9D', 'GBXU8', 'SQLSD', '125CL', 'OLOCN', '8H0ZP', '9H05U', '8V5IP', 'WHGBR', '272V6', 'PE6CV', 'Z6O6O', 'PIAB0', '2EBWH'], 'roll': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), 'math_scores': array([14, 37, 68,  8, 97, 95, 14, 52, 36, 10, 49, 96, 71, 67, 25, 35, 35,
       15, 90, 25, 78, 30, 10, 40, 40, 43, 66,  9, 98, 28]), 'physics_scores': array([81,  9, 24,  3,  4, 29, 75, 69, 18, 51, 90,  7,  2, 34, 51, 52, 97,
       43, 16, 27,  2, 68, 32, 37,  5, 51, 10, 39, 46, 72]), 'chemistry_scores': array([89, 34, 90, 42, 77, 65, 39, 70, 79,  0, 37, 55, 69, 20, 68, 23, 99,
       92, 88, 20, 77, 12, 56,  9, 92, 18, 58, 97,  6, 16])}

In [ ]:
##convert the scores_dict to a pandas dataframe

df = pd.DataFrame(scores_dict)
df.head()

      id  roll  math_scores  physics_scores  chemistry_scores
0  XFP1Q     1           14              81                89
1  LXFDN     2           37               9                34
2  1PEXT     3           68              24                90
3  QAQX0     4            8               3                42
4  QC0JJ     5           97               4                77

In [ ]:
##make id column the index of the dataframe
df = df.set_index('id')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, XFP1Q to 2EBWH
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   roll              30 non-null     int64
 1   math_scores       30 non-null     int64
 2   physics_scores    30 non-null     int64
 3   chemistry_scores  30 non-null     int64
dtypes: int64(4)
memory usage: 1.2+ KB

In [ ]:
##access individual columns
df['math_scores']

id
XFP1Q    14
LXFDN    37
1PEXT    68
QAQX0     8
QC0JJ    97
KUJR9    95
IFUWW    14
LRBV9    52
QNKW7    36
YSCXL    10
D0SEA    49
S123C    96
HBLQD    71
GKIW5    67
MJ8N5    25
K8DZ8    35
7XQ9D    35
GBXU8    15
SQLSD    90
125CL    25
OLOCN    78
8H0ZP    30
9H05U    10
8V5IP    40
WHGBR    40
272V6    43
PE6CV    66
Z6O6O     9
PIAB0    98
2EBWH    28
Name: math_scores, dtype: int64

In [ ]:
##dataframe as a 2d array
df.values[0]

array([ 1, 14, 81, 89])

## Indexers in Pandas - iloc and loc

In [ ]:
##access the 10th row
df.iloc[10]

roll                11
math_scores         49
physics_scores      90
chemistry_scores    37
Name: D0SEA, dtype: int64

In [ ]:
##access only math scores for the 10th row
df.iloc[10, 1]

49

In [ ]:
##access the first 5 rows of the first 2 columns
df.iloc[:5, :2]

       roll  math_scores
id
XFP1Q     1           14
LXFDN     2           37
1PEXT     3           68
QAQX0     4            8
QC0JJ     5           97

In [ ]:
##access values using labels
df.loc['LXFDN':, :'physics_scores']

       roll  math_scores  physics_scores
id
LXFDN     2           37               9
1PEXT     3           68              24
QAQX0     4            8               3
QC0JJ     5           97               4
KUJR9     6           95              29
IFUWW     7           14              75
LRBV9     8           52              69
QNKW7     9           36              18
YSCXL    10           10              51
D0SEA    11           49              90
S123C    12           96               7
HBLQD    13           71               2
GKIW5    14           67              34
MJ8N5    15           25              51
K8DZ8    16           35              52
7XQ9D    17           35              97
GBXU8    18           15              43
SQLSD    19           90              16
125CL    20           25              27
OLOCN    21           78               2
8H0ZP    22           30              68
9H05U    23           10              32
8V5IP    24           40              37
WHGBR    25           40               5
272V6    26           43              51
PE6CV    27           66              10
Z6O6O    28            9              39
PIAB0    29           98              46
2EBWH    30           28              72